### ISSUE TITLE
为什么总是报这种维度的错误？

### ISSUE THREAD

**Issue by lihea** [lsvih/Simple-Gimp-Captcha-Resolver#1]
RuntimeError: Given groups=1, weight of size [32, 1, 3, 3], expected input[64, 3, 64, 200] to have 1 channels, but got 3 channels instead

**Comment by lihea** [comment]
Loading train data...
Loading test data...
0 / 300 Epoch
  0%|                                                                                                                                                | 0/785 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 107, in <module>
    main()
  File "main.py", line 22, in main
    train(train_loader, val_loader)
  File "main.py", line 40, in train
    epoch_loss = train_epoch(train_loader, model, optimizer)
  File "main.py", line 54, in train_epoch
    for i, batch in enumerate(tqdm(train_loader)):
  File "/home/lihe/anaconda3/envs/yanzhengma36/lib/python3.6/site-packages/tqdm/std.py", line 1185, in __iter__
    for obj in iterable:
  File "/home/lihe/anaconda3/envs/yanzhengma36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/lihe/anaconda3/envs/yanzhengma36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/lihe/anaconda3/envs/yanzhengma36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/lihe/anaconda3/envs/yanzhengma36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/lihe/ktsh2/yanzhengma_cnn_att_lstm/dataloader.py", line 47, in __getitem__
    return to_tensor(img), [characters.index(i) for i in label]
  File "/home/lihe/anaconda3/envs/yanzhengma36/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 48, in to_tensor
    img = torch.from_numpy(pic.transpose((2, 0, 1)))
ValueError: axes don't match array

**Comment by lsvih** [comment]
你好，可能是 openCV 或者 torch 和 torchvision 这几个库的版本更新之后 api 发生了变动
